"""
PDF report generation for AI predictions
"""
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from io import BytesIO


def generate_pdf_report(record):
    """
    Generate a professional PDF medical AI report
    
    Args:
        record (dict): Prediction record with keys:
            - timestamp: datetime string
            - prediction: predicted class name
            - confidence: confidence value (0-1)
            - confidence_level: "High", "Moderate", "Low"
            
    Returns:
        BytesIO: PDF buffer ready for download
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    content = []

    # Title
    content.append(
        Paragraph("<b>AI Disease Prediction Report</b>", styles["Title"])
    )
    content.append(Spacer(1, 12))

    # Prediction details table
    table_data = [
        ["Timestamp", record["timestamp"]],
        ["Predicted Class", record["prediction"]],
        ["Confidence", f"{record['confidence']:.2%}"],
        ["Confidence Level", record["confidence_level"]],
    ]

    table = Table(table_data, colWidths=[150, 300])
    content.append(table)
    content.append(Spacer(1, 12))

    # Disclaimer
    content.append(
        Paragraph(
            "Disclaimer: This report is generated by an AI-based decision support system "
            "and must be reviewed by a qualified medical professional.",
            styles["Normal"],
        )
    )

    # Build PDF
    doc.build(content)
    buffer.seek(0)
    return buffer
